name: 'Setup TinyTeX'
description: 'Install release of TinyTeX'
inputs:
  directory:
    description: 'where to install TinyTeX. This path will be added to PATH.'
    required: true
    default: $RUNNER_TEMP/bin
  
runs:
  using: "composite"
  steps: 
    - name: Select extension according to OS
      run: |
        case $RUNNER_OS in 
          "Linux")
              echo "RELEASE_EXT=tar.gz" >> $GITHUB_ENV
              ;;
           "macOS")
              echo "RELEASE_EXT=tgz" >> $GITHUB_ENV
              ;;
           "Windows")
              echo "RELEASE_EXT=zip" >> $GITHUB_ENV
              ;;
            *)
              echo "$RUNNER_OS not supported"
              exit 1
              ;;
        esac
      shell: bash
    - name: Last release
      id: get-release
      env:
        GH_TOKEN: ${{ github.token }}
      run: | 
        echo ">> Will retrieve artifact for $RUNNER_OS"
        res=$(curl -H "Authorization: token $GH_TOKEN" $GITHUB_API_URL/repos/yihui/tinytex-releases/releases/latest)
        export RELEASE_REG=TinyTeX-v.*[.]$RELEASE_EXT$
        download_url=$(echo $res | jq -r '.assets[] | select(.browser_download_url | test(env.RELEASE_REG)) | .browser_download_url')
        echo "::set-output name=release::$(echo $download_url)"
      shell: bash
    - name: Download and install TinyTeX
      run: |
        echo ">> Will get the release $(basename ${{ steps.get-release.outputs.release }})"
        bundle=tinytex.$RELEASE_EXT
        curl -L -o $bundle ${{ steps.get-release.outputs.release }}
        mkdir -p ${{ inputs.directory }}
        echo ">> install in ${{ inputs.directory }}"
        [ ${{ runner.os }} == "Windows" ] && 7z x $bundle -o${{ inputs.directory }}
        [ ${{ runner.os }} != "Windows" ] && tar -C ${{ inputs.directory }} -xvzf $bundle 
        ls ${{ inputs.directory }}
        echo ">> Adding to PATH"
        [ ${{ runner.os }} == "Linux" ] && echo "${{ inputs.directory }}/.TinyTeX/bin" >> $GITHUB_PATH
        [ ${{ runner.os }} == "macOS" ] && echo "${{ inputs.directory }}/TinyTeX/bin" >> $GITHUB_PATH
        [ ${{ runner.os }} == "Windows" ] && echo "${{ inputs.directory }}/TinyTeX/bin/win32/" >> $GITHUB_PATH
        echo ">> TinyTeX installed"
      shell: bash
    - name: TinyTeX version
      run: |
        echo ">> tlmgr installed"
        echo $PATH
      shell: bash